apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-rollouts
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev
      - stage: staging 
      - stage: prod-amer-east
      - stage: prod-amer-west
      - stage: prod-emea
  template:
    metadata:
      name: demo-rollouts-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: demo-rollouts:{{stage}}
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack.sedemo: argo-notifications
        notifications.argoproj.io/subscriptions: |
          - trigger: [on-sync-succeeded, on-rollout-updated, on-rollout-step-completed]
            destinations:
              - service: slack
                recipients: [argo-notifications]
    spec:
      project: rollouts
      source:
        repoURL: https://github.com/akuity/sedemo-monorepo
        targetRevision: env-rollouts/{{stage}}
        path: .
      destination:
        name: sedemo-primary
        namespace: demo-{{stage}}
      syncPolicy:
        automated:
          prune: true
          enabled: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true