apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rollouts-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev
      - stage: staging 
      - stage: prod-amer-east
      - stage: prod-amer-west
      - stage: prod-emea
  template:
    metadata:
      name: rollouts-app-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: rollouts-app:{{stage}}
    spec:
      project: rollouts
      source:
        repoURL: https://github.com/eddiewebb/argodemo-rollouts-app
        targetRevision: env/{{stage}}
        path: .
      destination:
        name: sedemo-primary
        namespace: demo-{{stage}}
      syncPolicy:
        automated:
          prune: true
          enabled: false
          selfHeal: false
        syncOptions:
        - CreateNamespace=true