{{ if or ( .Values.environments.staging) (ne .Values.kargo.stage "staging") }}
apiVersion: v1
kind: Service
metadata:
  name: svc-stable
  annotations:
    prometheus.io/fastscrape: 'true'
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.image.containerPort }}
  selector:
    app: '{{ .Values.projectName }}-app'
{{- if .Values.rollouts.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-canary
  annotations:
    prometheus.io/fastscrape: 'true'
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.image.containerPort }}
  selector:
    app: '{{ .Values.projectName }}-app'
{{- end }}
{{ end }}