apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: team-emily-guestbook
  namespace: team-emily-guestbook
spec:
  promotionPolicies:
  - stageSelector:
      name: test
    autoPromotionEnabled: true
  - stageSelector:
      name: uat
    autoPromotionEnabled: true