{{ range $key, $val := .Values.environments }}
{{ if or ( $.Values.environments.staging) (ne $key "staging") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{$.Values.projectName}}-{{$key}}'
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    kargo.akuity.io/authorized-stage: '{{$.Values.projectName}}:{{$key}}'
    argocd.argoproj.io/sync-wave: "1" #create argo apps after kargo project created
spec:
  project: '{{$.Values.projectName}}'
  sources:
  #pull custom values from team managed monorepo folder
  - repoURL: https://github.com/akuity/sedemo-monorepo.git
    targetRevision: main
    ref: appValues 
  # apply to platform team managed kargo templates
  - targetRevision: HEAD
    repoURL: https://github.com/akuity/sedemo-platform
    path: templated-teams/apps-chart/
    helm:
      valueFiles:
      - '$appValues/templated/{{ $.Values.projectName }}/platform/app-values.yaml'
      valuesObject:
        repoUrl: https://github.com/akuity/sedemo-monorepo.git
        projectPath: templated/{{ $.Values.projectName }}
        projectName: '{{ $.Values.projectName }}'
        kargo:
          stage: '{{ $key }}'
  destination:
    name: sedemo-primary
    namespace: {{ $.Values.projectName }}-{{$key}}
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 2
---
{{ end }}
{{ end }}