{{ range $key, $val := .Values.environments }}
{{ if or ( $.Values.environments.staging) (ne $key "staging") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{$.Values.application.name}}-{{$key}}'
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    kargo.akuity.io/authorized-stage: '{{$.Values.application.name}}:{{$key}}'
    argocd.argoproj.io/sync-wave: "1" #create argo apps after kargo project created
spec:
  project: '{{$.Values.project.name}}'
  source:
  #pull custom values from team managed monorepo folder (rendered by Kargo)
    repoURL: '{{$.Values.repoUrl}}'
    targetRevision: env/{{ $.Values.application.name }}-{{$key}}
    path: .
  destination:
    name: sedemo-primary
    namespace: {{ $.Values.application.name }}-{{$key}}
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 2
---
{{ end }}
{{ end }}