apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{.Values.application.name}}-kargo'
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: '{{.Values.project.name}}'
  sources:
  #pull custom values from team managed monorepo folder
  - repoURL: {{.Values.repoUrl}}
    targetRevision: main
    ref: appValues 
  # apply to platform team managed kargo templates
  - targetRevision: HEAD
    repoURL: https://github.com/akuity/sedemo-platform
    path: templated-teams/kargo-chart/
    helm:
      valueFiles:
      - '$appValues/{{.Values.project.path}}/platform/app-values.yaml'
      valuesObject:
        chartUrl: https://github.com/akuity/sedemo-platform
        chartPath: templated-teams/apps-chart/
        repoUrl: {{.Values.repoUrl}}
        project:
          path: '{{.Values.project.path }}'
          name: '{{.Values.project.name}}'
        application:
          name: '{{.Values.application.name}}'
  destination:
    name: kargo
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true