apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{.Values.projectName}}-kargo'
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: '{{.Values.projectName}}'
  sources:
  #pull custom values from team managed monorepo folder
  - repoURL: https://github.com/akuity/sedemo-monorepo.git
    targetRevision: main
    ref: appValues 
  # apply to platform team managed kargo templates
  - targetRevision: HEAD
    repoURL: https://github.com/akuity/sedemo-platform
    path: templated-teams/kargo-chart/
    helm:
      valueFiles:
      - '$appValues/templated/{{.Values.projectName}}/platform/app-values.yaml'
      valuesObject:
        chartUrl: https://github.com/akuity/sedemo-platform
        chartPath: templated-teams/apps-chart/
        repoUrl: https://github.com/akuity/sedemo-monorepo.git
        projectPath: templated/{{.Values.projectName}}
        projectName: '{{.Values.projectName}}'
  destination:
    name: kargo
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true