apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-shard-eso
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev
      - stage: staging 
      - stage: prod
  template:
    metadata:
      name: local-shard-eso-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: local-shard-eso:{{stage}}
    spec:
      project: rollouts
      source:
        repoURL: https://github.com/akuity/sedemo-rollouts-app
        targetRevision: locked-env/{{stage}}
        path: .
      destination:
        name: sedemo-primary
        namespace: lockitdown-{{stage}}
      syncPolicy:
        automated:
          prune: true
          enabled: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true