
application:
  name: template

project:
  name: templated-name
  group: akuityio:demo
  path: templated/name

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/akuity/sedemo-monorepo-rollouts-app
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 218-yellow
  selectionStrategy: NewestBuild
  tagRegex: '^\d*-[a-z]*$'

kargo:
  stage: dev

git:
    main: main
    outPath: out
    srcPth: src


rollouts:
  enabled: true

environments:
  staging: true

services:
  s3: 
    enabled: false

notifications:
  slack:
    enabled: false