apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-intelligence
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev
      - stage: staging
      - stage: prod
  template:
    metadata:
      name: demo-intelligence-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: demo-intelligence:{{stage}}
    spec:
      project: demo-intelligence
      source:
        repoURL: https://github.com/akuity/sedemo-platform
        targetRevision: main
        path: charts/demo-intelligence/guestbook
        helm:
          releaseName: "{{stage}}"
          valueFiles:
          - values-{{stage}}.yaml
      destination:
        name: sedemo-primary
        namespace: demo-intelligence
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-intelligence-prod-oom
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: demo-intelligence:prod-oom
spec:
  project: demo-intelligence
  source:
    repoURL: https://github.com/akuity/sedemo-platform
    targetRevision: main
    path: apps/demo-intelligence/oom-demo
  destination:
    name: sedemo-primary
    namespace: demo-intelligence
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-intelligence-prod-crashloop
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: demo-intelligence:prod-crashloop
spec:
  project: demo-intelligence
  source:
    repoURL: https://github.com/akuity/sedemo-platform
    targetRevision: main
    path: apps/demo-intelligence/crashloop-demo
  destination:
    name: sedemo-primary
    namespace: demo-intelligence
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
