apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: components
  sources:
  - repoURL: https://github.com/akuity/sedemo-platform.git
    targetRevision: main
    ref: localValues 
    directory:
      recurse: true
  - chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 27.41.2
    helm:
      releaseName: prometheus
      # valuesObject:
      #   server:
      #     ingress:
      #       enabled: true
      #       ingressClassName: nginx
      #       path: /
      #       hosts:
      #       - prometheus.prometheus.k8s.orb.local
      valueFiles:
      - $localValues/components/value-overrides/prometheus-values.yaml
  destination:
        name: sedemo-primary
        namespace: prometheus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
