name: Kargo Setup
run-name: Run setup.sh for kargo creds
on:
  push:
    branches:
      - main
      - auto-credentials
    paths:
      - 'kargo/**'
      - '.github/workflows/run-kargo-setup.yaml'
permissions:
  contents: read
  actions: read
  id-token: write
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Seup Kargo CLI
        run: |
          curl -L -o /usr/local/bin/kargo https://github.com/akuity/kargo/releases/latest/download/kargo-linux-amd64
          chmod +x /usr/local/bin/kargo
      - name: Run Kargo Setup Script
        run: bash setup.sh