apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vgs-demo
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - stage: dev
          - stage: staging 
          - stage: password
  template:
    metadata:
      name: "{{appname}}-demo-{{stage}}"
      annotations:
        kargo.akuity.io/authorized-stage: "{{appname}}-demo:{{stage}}"
    spec:
      project: {{ .Values.projectName }}
      source:
        repoURL: {{ .Values.repoUrl }}
        targetRevision: env{{ .Values.projectName }}-{{stage}}
        path: .
      destination:
        name: sedemo-primary
        namespace: "{{ .Values.projectName }}-{{stage}}"
      syncPolicy:
        automated:
          prune: true
          enabled: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true