apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: '{{ .Values.projectName }}-apps'
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - stage: dev
        - stage: staging 
        - stage: prod
  template:
    metadata:
      name: '{{ .Values.projectName }}-demo-{{ printf "{{stage}}" }}'
      annotations:
        kargo.akuity.io/authorized-stage: '{{ .Values.projectName }}-demo:{{ printf "{{stage}}" }}'
    spec:
      project: {{ .Values.projectName }}
      source:
        repoURL: {{ .Values.repoUrl }}
        targetRevision: env-{{ .Values.projectName }}-{{ printf "{{stage}}" }}
        path: .
      destination:
        name: sedemo-primary
        namespace: '{{ .Values.projectName }}-{{ printf "{{stage}}" }}'
      syncPolicy:
        automated:
          prune: true
          enabled: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true