apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stable-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.kargo.stage }}.{{ .Values.ingress.custom_prefix }}.{{ .Values.ingress.root_domain }}"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: svc-stable
            port:
              number: 80