apiVersion: v1
kind: Service
metadata:
  name: svc-stable
  annotations:
    prometheus.io/fastscrape: 'true'
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: '{{ .Values.projectName }}-app'
---
apiVersion: v1
kind: Service
metadata:
  name: svc-canary
  annotations:
    prometheus.io/fastscrape: 'true'
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: '{{ .Values.projectName }}-app'